services:
  db:
    image: postgres:15-alpine
    container_name: agrokongo_db
    environment:
      POSTGRES_USER: agrokongo_user
      POSTGRES_PASSWORD: agrokongo_pass
      POSTGRES_DB: agrokongo_dev
    ports:
      - "5433:5432"  # Porta 5433 no host, 5432 no container
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    container_name: agrokongo_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
