"""empty message

Revision ID: 45f3403f01fc
Revises: 46b90ccd106d
Create Date: 2026-02-22 02:43:22.820227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '45f3403f01fc'
down_revision = '46b90ccd106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if inspector.has_table('movimentacoes_financeiras'):
        try:
            with op.batch_alter_table('movimentacoes_financeiras', schema=None) as batch_op:
                batch_op.alter_column('tipo',
                       existing_type=sa.VARCHAR(length=20),
                       type_=sa.String(length=30),
                       existing_nullable=False)
        except Exception:
            pass

    if inspector.has_table('transacoes'):
        try:
            with op.batch_alter_table('transacoes', schema=None) as batch_op:
                try:
                    batch_op.drop_constraint('uq_transacoes_fatura_ref', type_='unique')
                except Exception:
                    pass
                try:
                    batch_op.create_index(batch_op.f('ix_transacoes_fatura_ref'), ['fatura_ref'], unique=True)
                except Exception:
                    pass
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if inspector.has_table('transacoes'):
        try:
            with op.batch_alter_table('transacoes', schema=None) as batch_op:
                try:
                    batch_op.drop_index(batch_op.f('ix_transacoes_fatura_ref'))
                except Exception:
                    pass
                try:
                    batch_op.create_unique_constraint('uq_transacoes_fatura_ref', ['fatura_ref'], postgresql_nulls_not_distinct=False)
                except Exception:
                    pass
        except Exception:
            pass

    if inspector.has_table('movimentacoes_financeiras'):
        try:
            with op.batch_alter_table('movimentacoes_financeiras', schema=None) as batch_op:
                batch_op.alter_column('tipo',
                       existing_type=sa.String(length=30),
                       type_=sa.VARCHAR(length=20),
                       existing_nullable=False)
        except Exception:
            pass

    # ### end Alembic commands ###
