"""initial schema

Revision ID: 46b90ccd106d
Revises: 
Create Date: 2026-02-20 01:31:09.712386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b90ccd106d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produtos')),
    sa.UniqueConstraint('nome', name=op.f('uq_produtos_nome'))
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provincias')),
    sa.UniqueConstraint('nome', name=op.f('uq_provincias_nome'))
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], name=op.f('fk_municipios_provincia_id_provincias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_municipios'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telemovel', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('rating_vendedor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('vendas_concluidas', sa.Integer(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=150), nullable=True),
    sa.Column('documento_pdf', sa.String(length=150), nullable=True),
    sa.Column('perfil_completo', sa.Boolean(), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('conta_validada', sa.Boolean(), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], name=op.f('fk_usuarios_municipio_id_municipios')),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], name=op.f('fk_usuarios_provincia_id_provincias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('nif', name=op.f('uq_usuarios_nif'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_conta_validada'), ['conta_validada'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_telemovel'), ['telemovel'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_tipo'), ['tipo'], unique=False)

    op.create_table('alertas_preferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_alertas_preferencias_produto_id_produtos')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_alertas_preferencias_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alertas_preferencias'))
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_logs_auditoria_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs_auditoria'))
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_notificacoes_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacoes'))
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_lida'), ['lida'], unique=False)

    op.create_table('safras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_por_unidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagem', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('preco_por_unidade > 0', name=op.f('ck_safras_check_preco_positivo')),
    sa.CheckConstraint('quantidade_disponivel >= 0', name=op.f('ck_safras_check_quantidade_positiva')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_safras_produto_id_produtos')),
    sa.ForeignKeyConstraint(['produtor_id'], ['usuarios.id'], name=op.f('fk_safras_produtor_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safras'))
    )
    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.create_index('idx_safra_prod_status', ['produto_id', 'status'], unique=False)

    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_ref', sa.String(length=20), nullable=False),
    sa.Column('safra_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_comprada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total_pago', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comissao_plataforma', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_liquido_vendedor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comprovativo_path', sa.String(length=150), nullable=True),
    sa.Column('comprovativo_hash', sa.String(length=64), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previsao_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transferencia_concluida', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.id'], name=op.f('fk_transacoes_comprador_id_usuarios')),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], name=op.f('fk_transacoes_safra_id_safras')),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('fk_transacoes_vendedor_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transacoes')),
    sa.UniqueConstraint('fatura_ref', name=op.f('uq_transacoes_fatura_ref'))
    )
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacoes_status'), ['status'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], name=op.f('fk_avaliacoes_transacao_id_transacoes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacoes'))
    )
    op.create_table('historico_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=True),
    sa.Column('data_mudanca', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], name=op.f('fk_historico_status_transacao_id_transacoes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico_status'))
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], name=op.f('fk_mensagens_destinatario_id_usuarios')),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], name=op.f('fk_mensagens_remetente_id_usuarios')),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], name=op.f('fk_mensagens_transacao_id_transacoes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagens'))
    )
    op.create_table('movimentacoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], name=op.f('fk_movimentacoes_financeiras_transacao_id_transacoes')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_movimentacoes_financeiras_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacoes_financeiras'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_financeiras')
    op.drop_table('mensagens')
    op.drop_table('historico_status')
    op.drop_table('avaliacoes')
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacoes_status'))

    op.drop_table('transacoes')
    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.drop_index('idx_safra_prod_status')

    op.drop_table('safras')
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_lida'))

    op.drop_table('notificacoes')
    op.drop_table('logs_auditoria')
    op.drop_table('alertas_preferencias')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_tipo'))
        batch_op.drop_index(batch_op.f('ix_usuarios_telemovel'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_conta_validada'))

    op.drop_table('usuarios')
    op.drop_table('municipios')
    op.drop_table('provincias')
    op.drop_table('produtos')
    # ### end Alembic commands ###
