"""adicionar campos de logística à transação

Revision ID: 6ffe380dbcab
Revises: 46b90ccd106d
Create Date: 2026-02-05 02:04:27.595612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffe380dbcab'
down_revision = '46b90ccd106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('transacoes', schema=None) as batch_op:
            batch_op.add_column(sa.Column('previsao_entrega', sa.DateTime(timezone=True), nullable=True))
    except Exception:
        # SQLite pode já ter a coluna criada (ou a operação pode ser re-executada)
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('transacoes', schema=None) as batch_op:
            batch_op.drop_column('previsao_entrega')
    except Exception:
        pass

    # ### end Alembic commands ###
