"""Adicionar UUID para proteção contra enumeração de IDs

Revision ID: adicionar_uuid_transacoes
Revises: 001_correcoes_agrokongo
Create Date: 2026-02-28 05:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = 'adicionar_uuid_transacoes'
down_revision = '001_correcoes_agrokongo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar coluna UUID (compatível com SQLite)
    # - Em SQLite não existe função uuid() por default, por isso não usamos server_default.
    # - Tornamos nullable=True para não falhar em tabelas já com dados.
    try:
        op.add_column('transacoes', sa.Column('uuid', sa.String(36), nullable=True))
    except Exception:
        pass

    # Gerar UUIDs para transações existentes (SQLAlchemy 2.x requer sa.text)
    connection = op.get_bind()
    try:
        rows = connection.execute(sa.text("SELECT id FROM transacoes"))
        for row in rows:
            trans_id = row[0]
            new_uuid = str(uuid.uuid4())
            connection.execute(
                sa.text("UPDATE transacoes SET uuid = :u WHERE id = :id"),
                {"u": new_uuid, "id": trans_id},
            )
    except Exception:
        # Se a tabela não existir ou já tiver UUIDs preenchidos, não bloqueia o upgrade
        pass

    # Criar índice único para UUID (idempotente)
    try:
        op.create_index('ix_transacoes_uuid', 'transacoes', ['uuid'], unique=True)
    except Exception:
        pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_transacoes_uuid', table_name='transacoes')
    except Exception:
        pass
    try:
        op.drop_column('transacoes', 'uuid')
    except Exception:
        pass
    # ### end Alembic commands ###
