"""empty message

Revision ID: afef678e5fe9
Revises: 45f3403f01fc
Create Date: 2026-02-23 03:43:04.758294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'afef678e5fe9'
down_revision = '45f3403f01fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if not inspector.has_table('pagamentos_logs'):
        try:
            op.create_table('pagamentos_logs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('trans_id', sa.String(length=50), nullable=False),
            sa.Column('valor_liquidado', sa.Numeric(precision=14, scale=2), nullable=True),
            sa.Column('acao', sa.String(length=50), nullable=True),
            sa.Column('detalhes', sa.Text(), nullable=True),
            sa.Column('data', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos_logs'))
            )
        except Exception:
            pass

    if inspector.has_table('pagamentos_logs'):
        try:
            with op.batch_alter_table('pagamentos_logs', schema=None) as batch_op:
                try:
                    batch_op.create_index(batch_op.f('ix_pagamentos_logs_trans_id'), ['trans_id'], unique=False)
                except Exception:
                    pass
        except Exception:
            pass

    if inspector.has_table('transacoes'):
        try:
            with op.batch_alter_table('transacoes', schema=None) as batch_op:
                try:
                    batch_op.add_column(sa.Column('data_liquidacao', sa.DateTime(timezone=True), nullable=True))
                except Exception:
                    pass
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if inspector.has_table('transacoes'):
        try:
            with op.batch_alter_table('transacoes', schema=None) as batch_op:
                try:
                    batch_op.drop_column('data_liquidacao')
                except Exception:
                    pass
        except Exception:
            pass

    if inspector.has_table('pagamentos_logs'):
        try:
            with op.batch_alter_table('pagamentos_logs', schema=None) as batch_op:
                try:
                    batch_op.drop_index(batch_op.f('ix_pagamentos_logs_trans_id'))
                except Exception:
                    pass
        except Exception:
            pass

        try:
            op.drop_table('pagamentos_logs')
        except Exception:
            pass
    # ### end Alembic commands ###
