"""Criar tabela de disputas com todas as regras RN05-RN08

Revision ID: criar_tabela_disputas
Revises: adicionar_uuid_transacoes
Create Date: 2026-02-28 05:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'criar_tabela_disputas'
down_revision = 'adicionar_uuid_transacoes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar tabela disputas
    op.create_table('disputas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transacao_id', sa.Integer(), nullable=False),
        sa.Column('comprador_id', sa.Integer(), nullable=False),
        sa.Column('motivo', sa.Text(), nullable=False),
        sa.Column('evidencia_path', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True, server_default='aberta'),
        sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=True),
        sa.Column('data_resolucao', sa.DateTime(timezone=True), nullable=True),
        sa.Column('admin_responsavel_id', sa.Integer(), nullable=True),
        sa.Column('decisao_justificativa', sa.Text(), nullable=True),
        sa.Column('taxa_administrativa', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['admin_responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('motivo IS NOT NULL AND motivo != ""', name='ck_motivo_obrigatorio')
    )
    
    # Criar índices
    op.create_index('ix_disputas_status', 'disputas', ['status'])
    op.create_index('ix_disputas_data_abertura', 'disputas', ['data_abertura'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disputas_data_abertura', table_name='disputas')
    op.drop_index('ix_disputas_status', table_name='disputas')
    op.drop_table('disputas')
    # ### end Alembic commands ###
