"""Implementar status_conta textuais e tabela carteiras separada
Alinha com caso de uso: PENDENTE_VERIFICACAO -> VERIFICADO

Revision ID: implementar_status_conta_carteiras
Revises: criar_tabela_disputas
Create Date: 2026-02-28 05:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'implementar_status_conta_carteiras'
down_revision = 'criar_tabela_disputas'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect = getattr(bind, "dialect", None)
    dialect_name = getattr(dialect, "name", "")
    
    # 1. Adicionar coluna status_conta
    try:
        op.add_column('usuarios', sa.Column('status_conta', sa.String(length=20), nullable=False, server_default='PENDENTE_VERIFICACAO'))
    except Exception:
        pass
    
    # 2. Criar índice para status_conta
    try:
        op.create_index('ix_usuarios_status_conta', 'usuarios', ['status_conta'], unique=False)
    except Exception:
        pass
    
    # 3. Migrar dados existentes de conta_validada para status_conta
    try:
        # SQLite não tem boolean literal true/false em todas as configs; usa 1/0.
        if dialect_name == 'sqlite':
            op.execute("""
                UPDATE usuarios
                SET status_conta = CASE
                    WHEN conta_validada = 1 THEN 'VERIFICADO'
                    ELSE 'PENDENTE_VERIFICACAO'
                END
            """)
        else:
            op.execute("""
                UPDATE usuarios 
                SET status_conta = CASE 
                    WHEN conta_validada = true THEN 'VERIFICADO'
                    ELSE 'PENDENTE_VERIFICACAO'
                END
            """)
    except Exception:
        pass
    
    # 4. Criar tabela carteiras
    try:
        op.create_table('carteiras',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('usuario_id', sa.Integer(), nullable=False),
            sa.Column('saldo_disponivel', sa.Numeric(precision=14, scale=2), nullable=True),
            sa.Column('saldo_bloqueado', sa.Numeric(precision=14, scale=2), nullable=True, server_default='0.00'),
            sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
            sa.Column('data_ultima_atualizacao', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.CheckConstraint('saldo_disponivel >= 0', name='ck_saldo_disponivel_pos'),
            sa.CheckConstraint('saldo_bloqueado >= 0', name='ck_saldo_bloqueado_pos'),
            sa.UniqueConstraint('usuario_id', name='uq_carteira_usuario')
        )
    except Exception:
        pass
    
    # 5. Criar índices para carteiras
    try:
        op.create_index('ix_carteiras_usuario_id', 'carteiras', ['usuario_id'], unique=True)
    except Exception:
        pass
    
    # 6. Criar carteiras para usuários existentes
    try:
        # Evitar duplicar carteiras quando re-executa: só insere se não existir
        op.execute("""
            INSERT INTO carteiras (usuario_id, saldo_disponivel, data_criacao, data_ultima_atualizacao)
            SELECT 
                u.id, 
                COALESCE(u.saldo_disponivel, 0.00),
                u.data_cadastro,
                u.data_cadastro
            FROM usuarios u
            WHERE NOT EXISTS (
                SELECT 1 FROM carteiras c WHERE c.usuario_id = u.id
            )
        """)
    except Exception:
        pass
    
    # 7. Criar trigger para criação automática de carteira
    if dialect_name != 'sqlite':
        op.execute("""
            CREATE OR REPLACE FUNCTION criar_carteira_usuario()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO carteiras (usuario_id, saldo_disponivel, data_criacao, data_ultima_atualizacao)
                VALUES (NEW.id, 0.00, NOW(), NOW());
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)
        
        op.execute("""
            CREATE TRIGGER trigger_criar_carteira_usuario
            AFTER INSERT ON usuarios
            FOR EACH ROW
            EXECUTE FUNCTION criar_carteira_usuario();
        """)
    
    # 8. Criar função para atualização de saldo
    if dialect_name != 'sqlite':
        op.execute("""
            CREATE OR REPLACE FUNCTION atualizar_saldo_carteira()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE carteiras 
                SET saldo_disponivel = NEW.saldo_disponivel,
                    data_ultima_atualizacao = NOW()
                WHERE usuario_id = NEW.id;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)
        
        op.execute("""
            CREATE TRIGGER trigger_atualizar_saldo_carteira
            AFTER UPDATE OF saldo_disponivel ON usuarios
            FOR EACH ROW
            WHEN (OLD.saldo_disponivel IS DISTINCT FROM NEW.saldo_disponivel)
            EXECUTE FUNCTION atualizar_saldo_carteira();
        """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover triggers
    op.execute("DROP TRIGGER IF EXISTS trigger_atualizar_saldo_carteira")
    op.execute("DROP FUNCTION IF EXISTS atualizar_saldo_carteira")
    op.execute("DROP TRIGGER IF EXISTS trigger_criar_carteira_usuario")
    op.execute("DROP FUNCTION IF EXISTS criar_carteira_usuario")
    
    # Remover índices
    op.drop_index('ix_carteiras_usuario_id', table_name='carteiras')
    op.drop_index('ix_usuarios_status_conta', table_name='usuarios')
    
    # Remover tabela carteiras
    op.drop_table('carteiras')
    
    # Remover coluna status_conta
    op.drop_column('usuarios', 'status_conta')
    
    # ### end Alembic commands ###
